### ISSUE TITLE
[Suggestion] Connected Textures

### ISSUE THREAD

**Issue by Sk4nd4L** [Flanks255/simplylight#10]
Hi I was wondering if you could add an option somehow to connect textures when multiple light blocks are placed next to each other. I love your mod and this would make it even more awesome! Thanks for considering and thanks for making this great mod!!! 🥇 :)

**Comment by Flanks255** [comment]
Added ctm support for the slabs and panels in the newest 1.16 version, the full blocks sometime soon hopefully.
