### ISSUE TITLE
Dynamic Edge Light

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [Flanks255/simplylight#12]
**Describe the bug**
Dynamic Edge Lights do not think the drawers from Storage Drawers Mod (version: 7.0.2)(by Texelsaur) as wall so they become squares.

Forge version: 1.15.2-31.2.20
Mod version: 0.9.0

**Screenshots**
![2020-06-21_20 07 10](https://user-images.githubusercontent.com/36394415/85224228-5015f180-b3fb-11ea-9a4c-6005644f5161.png)

**Comment by Flanks255** [comment]
So, that does happen with the front of the drawers, in a way its the correct way, as the fronts are not solid surfaces, in 1.12 i just asked the block if it was solid, but now its based off the voxel data, and the fronts of the drawers are technically not solid.

**Comment by ShinyRayquaza9923** [comment]
I guess that makes sense.. It would be nice if there's a way to change the shape manually or what if there is a new edge light that is not dynamic? Will that be asking to much? :|
Also, I saw someone suggested for a vertical edge light and you said it's not possible until 1.13. Will it be possible for 1.15?
Love your mod anyhows. :)
