### ISSUE TITLE
1.16 Question

### ISSUE THREAD

**Issue by traveldesign** [Flanks255/simplylight#13]
Hi, I didn't know where else to ask this so forgive me if it's the wrong place! I love the mod and I've used it for a year now. I was just wondering if you have any plans to update it to 1.16? Thanks for all your hard work and creativity! :)

**Comment by Flanks255** [comment]
Very much so, just haven't gotten to it yet, should take long once i start at it.
I'll leave this issue open and close it when i release the 1.16 version so you get notified.

**Comment by traveldesign** [comment]
Thanks for updating it! You rock :)
