### ISSUE TITLE
Question about lag

### ISSUE THREAD

**Issue by traveldesign** [Flanks255/simplylight#14]
Hi there, 

Thanks so much for updating the mod to 1.16. It's one of my favorites! I have a random question for you.

Do you think that having lots of your powered blocks (always on) in my world would cause lag? 
My doubt comes from what people say about having too much redstone related blocks in your world (because having too many circuits causes lag). 

The reason I ask is because I'm in the process of building a big industrial room underground and I want to use your blocks to light up the whole thing. As you might imagine it's going to take a lot of them.

Anyway, I hope my question makes sense. Thanks for your help!

**Comment by Flanks255** [comment]
Hey, it should be fine, my whole intention for the mod was to be as lag free as possible.
The block form of the lights(the only one that interacts with redstone) only checks its redstone value on a block update, so it should be fine, as well it is a full block, so a simple cube.
The rest of the lights should be fine too, they only calculate state when you place them, after that they are inert.
