### ISSUE TITLE
1.16.4 Compat

### ISSUE THREAD

**Issue by traveldesign** [Flanks255/simplylight#17]
Hi, I was wondering if Simply Light is compatible with 1.16.4. I've seen other mods that say that their 1.16.3 versions work with 1.16.4 as well. Thanks! Your mod is one of the best out there for modern lights!

**Comment by Flanks255** [comment]
If you are on forge 35.0.5 or higher it should, I hadn't thought of marking
it for forward compatibility when I uploaded the current version, but that
forge version makes it work anyway, I'm planning on releasing something
soon, but the backwards compact in 35.0.5 should make it fine to load.

**Comment by traveldesign** [comment]
Ok great I'll try it. Random question. Are you adding any new content to the mod in the near future? I love your creativity.

**Comment by Flanks255** [comment]
right now im working on refactoring everything to make it alot cleaner since ive learned alot lately, better ways of doing everything etc. other then that, i do have a couple near future things im wanting todo, like colored lights(the block, colored light itself isnt possible).

**Comment by traveldesign** [comment]
Colored lights sound legit. I wish colored light was possible too. I guess it is on RTX. 

Sorry for my ignorance, but what do you mean by refactoring?
