### ISSUE TITLE
1.12.2 support

### ISSUE THREAD

**Issue by kitkam** [Flanks255/simplylight#18]
I have a modded minecraft server that me and my friends are trying to build a city with. We recently switched from 1.16.3 to 1.12.2 so that we could gain access to more mods. We downloaded the 1.12.2 version of Simply Light but it caused the server to immediately crash. I can give you a list of the mods, maybe you can figure out which mod is conflicting or what it is that is causing it to crash? I don't much about code, but I know i cant find any other good lighting mod like Simply light that would look good in the server. So if you could help out, id really appreciate it <3 

Heres the list of the mods (currently) on the server: 

- Aquaculture
- Better Animals Plus
- Chisels and Bits
- Coroutil and Corosus Weather Mod
- cosmetic beds
- Expanded UNUverse Pack
- UNU Civilian, Military, and Parts packs
- Furenikus Roads
- Immersive Vehicles, and Railroading
- Crayfishs Vehicles and Furniture
- Trin Civil, Emergency, and Part packs
- Macaws furniture, roofs, windows and doors
- Moonspire Metropolitan Motors
- MTS Official Pack
- Obfuscate
- Quick Homes
- RS Switches and Gauges
- Trackside Decor
- Waddles
- Wayward Craft [removed]
- Signpost
- Univeral Mod Core
- Track API
- Malice Core and Doors
- Macro Automotive Industries
- Melvins Simple Sign Pack
- Miszko Vehicle Pack
- Moving Elevators
- and some other mods that got added more recently. 

I'm not going to include the list of mods we recently got since we got them after we gave up trying to get Simply Light to work. 

Again, thank you and I hope you can help.

**Comment by Flanks255** [comment]
crash log?

**Comment by kitkam** [comment]
i'm currently trying to see if I can get access to it

**Comment by kitkam** [comment]
okay i got a crash log from just installing the mod and trying to load up minecraft. do you want me to just ctrl+a  and paste the whole thing?

**Comment by kitkam** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.2.0_Forge_1.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.11.11_Forge_1.12.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/12/21 8:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simply Light (simplylight)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.shadowfacts.forgelin.KotlinAdapter
	at net.minecraftforge.fml.common.FMLModContainer.getLanguageAdapter(FMLModContainer.java:172)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:596)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.shadowfacts.forgelin.KotlinAdapter
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.getLanguageAdapter(FMLModContainer.java:167)
	... 36 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 570982784 bytes (544 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version               | Source                                                      | Signature                                |
	|:----- |:-------------------- |:--------------------- |:----------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft            | 1.12.2                | minecraft.jar                                               | None                                     |
	| LC    | mcp                  | 9.42                  | minecraft.jar                                               | None                                     |
	| LC    | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | xaerominimap_core    | 1.12.2-1.0            | minecraft.jar                                               | None                                     |
	| LC    | xaeroworldmap_core   | 1.12.2-1.0            | minecraft.jar                                               | None                                     |
	| LC    | obfuscate            | 0.4.2                 | minecraft.jar                                               | None                                     |
	| LC    | aquaculture          | 1.6.8                 | Aquaculture-1.12.2-1.6.8.jar                                | None                                     |
	| LC    | chiselsandbits       | 14.33                 | chiselsandbits-14.33.jar                                    | None                                     |
	| LC    | extendedrenderer     | v1.0                  | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
	| LC    | coroutil             | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
	| LC    | configmod            | v1.0                  | coroutil-1.12.1-1.2.37.jar                                  | None                                     |
	| LC    | cosmeticbeds         | 1.12.2-1.0.2.2        | cosmeticbeds-1.12.2-1.0.2.2.jar                             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | mts                  | 19.14.0               | Immersive+Vehicles-1.12.2-19.14.0.jar                       | None                                     |
	| LC    | unuparts             | 4.1.0                 | UNU+Parts+Pack+[MTS]+1.12.2-19.14.0-4.1.0.jar               | None                                     |
	| LC    | unuverse             | 1.3.0                 | Expanded+UNUverse+Pack+[MTS]+1.12.2-18.0.0-1.3.0.jar        | None                                     |
	| LC    | furenikusroads       | 1.1.10                | Fureniku's+Roads-1.1.10.jar                                 | None                                     |
	| LC    | cfm                  | 6.3.1                 | furniture-6.3.1-1.12.2.jar                                  | None                                     |
	| LC    | immersiveengineering | 0.12-98               | ImmersiveEngineering-0.12-98.jar                            | None                                     |
	| LC    | immersivepetroleum   | 1.1.9                 | immersivepetroleum-1.12.2-1.1.9.jar                         | None                                     |
	| LC    | trackapi             | 1.2                   | TrackAPI-1.2.jar                                            | None                                     |
	| LC    | universalmodcore     | 1.0.1                 | UniversalModCore-1.12.2-forge-1.0.1.jar                     | None                                     |
	| LC    | immersiverailroading | 1.8.0-7e0f82          | ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f821.jar         | None                                     |
	| LC    | iv_tcp_v3            | 3.0.0                 | IV_Trin_Civil_Pack_V3.9.0.jar                               | None                                     |
	| LC    | iv_tep               | 1.0.0                 | IV_Trin_Emergency_Pack_1.2.3.jar                            | None                                     |
	| LC    | iv_tpp               | 2.0.0                 | IV_Trin_Part_Pack_2.15.0.jar                                | None                                     |
	| LC    | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                                | None                                     |
	| LC    | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                               | None                                     |
	| LC    | mcwbridges           | 1.0.4                 | mcw-bridges-1.0.4-mc1.12.2.jar                              | None                                     |
	| LC    | mcwdoors             | 1.0                   | mcw-doors-1.0.0-mc1.12.2.jar                                | None                                     |
	| LC    | mcwfurnitures        | 1.0                   | mcw-furnitures-1.0.0-mc1.12.2.jar                           | None                                     |
	| LC    | mcwroofs             | 1.0.2                 | mcw-roofs-1.0.2-mc1.12.2.jar                                | None                                     |
	| LC    | mcwwindows           | 1.0                   | mcw-windows-1.0.0-mc1.12.2.jar                              | None                                     |
	| LC    | melvinssignpack      | 1.0.0                 | Melvins_Simple_Sign_Pack-Release-1.0.jar                    | None                                     |
	| LC    | mmmpack              | 1.1.0                 | Moonspire+Metropolitan+Motors+[MTS]+1.10.2-15.5.0-1.1.0.jar | None                                     |
	| LC    | movingelevators      | 1.2.33                | movingelevators-1.2.33-mc1.12.jar                           | None                                     |
	| LC    | quickhomes           | 1.2.2                 | QuickHomes-1.2.2.jar                                        | None                                     |
	| LC    | rsgauges             | 1.2.5                 | rsgauges-1.12.2-1.2.5.jar                                   | ed58ed655893ced6280650866985abcae2bf7559 |
	| LC    | signpost             | 1.08.5                | signpost-1.12.2-1.08.5.jar                                  | None                                     |
	| LE    | simplylight          | 1.12.2-0.8.7          | simplylight-1.12.2-0.8.7.jar                                | None                                     |
	| L     | signal_stuff         | 2.2                   | Trackside_Decor_2.2.jar                                     | None                                     |
	| L     | unucivil             | 4.1.0                 | UNU+Civilian+Pack+[MTS]+1.12.2-19.14.0-4.1.0.jar            | None                                     |
	| L     | unumilitary          | 3.5.1                 | UNU+Military+Pack+[MTS]+1.12.2-18.0.0-3.5.1.jar             | None                                     |
	| L     | vehicle              | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                               | None                                     |
	| L     | waddles              | 0.6.0                 | Waddles-1.12.2-0.6.0.jar                                    | None                                     |
	| L     | weather2             | 1.12.1-2.6.12         | weather2-1.12.1-2.6.12.jar                                  | None                                     |
	| L     | xaerominimap         | 21.2.0                | Xaeros_Minimap_21.2.0_Forge_1.12.jar                        | None                                     |
	| L     | xaeroworldmap        | 1.11.11               | XaerosWorldMap_1.11.11_Forge_1.12.jar                       | None                                     |
	| L     | betteranimalsplus    | 9.0.1                 | betteranimalsplus-1.12.2-9.0.1.jar                          | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_21.2.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
XaeroWorldMapPlugin (XaerosWorldMap_1.11.11_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.09' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.09
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Flanks255** [comment]
You are missing forgelin, the dependency for the 1.12 version.
https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin

**Comment by kitkam** [comment]
Ah, thank you! I didnt realize it required a dependency for 12.2. 

Also im not sure if its the amount of mods but im not seeing the "simply lights" tab for all the items in creative.  I double and triple checked to see if i  missed it, but its not there. I can look up the items and get them that way but the tab with all all the collective items is missing. 

Any ideas on how to fix this?

**Comment by Flanks255** [comment]
Looks like in 1.12 they were all in the decorations tab of creative. If that's what you are talking about
