### ISSUE TITLE
Simple Bulbs Placed Using Building Gadget Mod Appear As Waterlogged

### ISSUE THREAD

**Issue by mkleiman312** [Flanks255/simplylight#20]
Simply Light 1.16.4-1.1.2

Using Building Gadgets Mod (3.8.0) (All The Mods To The Sky), Simple Bulbs placed with the Building Gadget or the Copy-Paste Gadget appear as the waterlogged version. I don't know if this is an issue with your mod or DW20's.

**Comment by Flanks255** [comment]
Related: Direwolf20-MC/BuildingGadgets#579
