### ISSUE TITLE
Rolling Stock does not exist on server? (Train Stopping Buffer Issue)

### ISSUE THREAD

**Issue by Ethan4life84** [Flanks255/simplylight#22]
**Description of the bug**
So as I was adding the mod to my server, it would not allow for me to place the Bumpers (the one's listed as a locomotive) No matter what I did, they would NOT work. I can't add it to the config file like it asks due to it being a java file, so im left with nothing... if anyone can please help, it would be greatly appreciated.

**Screenshots**
![image](https://user-images.githubusercontent.com/83177099/118564549-801a6180-b73e-11eb-926e-4d8cbc69b826.png)

Please provide the version of forge used, and the mod version.
The Version of Forge used was Minecraft Forge 1.12.2 (14.23.5.2855)
and the Mod Version used was Trackside_Decor_2.2

**Comment by Flanks255** [comment]
i think you want this page: https://www.curseforge.com/minecraft/mc-mods/trackside-decor/issues
