### ISSUE TITLE
Simply Light encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by oceanderp** [Flanks255/simplylight#24]
**Describe the bug**
The mod won't work. 

**Screenshots**

[image](https://imgur.com/a/U2QDKKv)

Please provide the version of forge used, and the mod version.

1.171, Forge 37.0.33

**Comment by Flanks255** [comment]
I'm pretty sure forge made a breaking change in 37.0.31, I'm going to look
into it soon.
