### ISSUE TITLE
fabric  support?

### ISSUE THREAD

**Issue by masiro23** [Flanks255/simplylight#26]
fabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabricfabric

**Comment by Flanks255** [comment]
While I don't have anything against fabric, I'm not planning on it at this moment, please don't spam...
