### ISSUE TITLE
Simply Light fails to load.

### ISSUE THREAD

**Issue by keatonbuilder** [Flanks255/simplylight#30]
**Describe the bug**
The mod doesn't load.

**Screenshots**
<image src="https://cdn.discordapp.com/attachments/876442194377080872/1000512651929063464/unknown.png">
Crash Log: https://gist.github.com/keatonbuilder/84fb6badf5665d857601819389d3b99b

Forge Version: 41.0.110

Simply Light Version: 1.4.2 Build 35

**Comment by Flanks255** [comment]
update to 1.4.4,  your forge is too new for 1.4.2
