### ISSUE TITLE
Inverted Illuminant lights wont craft [fabric]

### ISSUE THREAD

**Issue by Z1MOTHY** [Flanks255/simplylight#31]
i crafted inverted illuminant blocks but when i use the recipes, there is no end product. it will not even let me craft them into regular illuminant blocks.

this is on fabric version 0.14.8 for 1.19

**Comment by Flanks255** [comment]
the other colors work right? looks like the toggle recipes are missing from the uncolored ones...

**Comment by Flanks255** [comment]
i would try 1.4.3 for fabric, should fix you up.
