### ISSUE TITLE
Unability to use

### ISSUE THREAD

**Issue by FrostyFireBoi** [Flanks255/simplylight#32]
Whenever I try to use the mod it says that it has failed to load correctly. Other mods that I am using dont show any problem. You can see the details in the picture of the problem.

I am using this mod in my server made in aternos. Its software is Forge 1.19. The server doesnt show any issue and looks to be working good but the problem is that if I cant use this mod then I cant play in my server. I play cracked minecraft through T launcher. The version is 1.19 Forge and I can use mods in it and also see which mods I have but when I use this mod, it shows me the screen of which I sent the picture.

![Screenshot (2)](https://user-images.githubusercontent.com/110128972/181357754-d1021eeb-2dd0-4064-8e10-bf1540429756.png)

**Comment by Flanks255** [comment]
mod version? forge version?

**Comment by FrostyFireBoi** [comment]
I downloaded the latest file for 1.19 from the forge website. I don't really know what forge version is but the problem lies in the fact that I can't use it but I can use the other mods. I told that the version I am trying to use in is 1.19

**Comment by Flanks255** [comment]
right, but forge broke stuff at various points in 1.19, simply light 1.4.2 works until you hit forge 41.0.64, then you need 1.4.3
then once you hit forge 41.0.94, you need simply light 1.4.4, because forge kept breaking things.
so both the version of the mod, and version of forge matter.

**Comment by FrostyFireBoi** [comment]
Your information is very helpful. I checked and the forge version I am playing on is 41.0.110, so will there be like a new version of simply light for this version of forge?

**Comment by Flanks255** [comment]
1.4.4 works from forge 41.0.94 onwards, it may even work on 1.19.1, i am about to test that.

**Comment by FrostyFireBoi** [comment]
Man thanks for the help the problem is fixed now.
