### ISSUE TITLE
[1.18.2/1.19.x] Illuminant fixture marked as full block.

### ISSUE THREAD

**Issue by CopCorvette** [Flanks255/simplylight#34]
when illuminant fixture is placed above grass the grass turn into dirt like when a full block is placed above grass.

![2022-10-25_11 18 50](https://user-images.githubusercontent.com/71981755/197799763-28fc96d3-5ab7-4b09-86a1-52748ca97921.png)

**Comment by Flanks255** [comment]
puzzling, doesnt happen for me, i even cranked randomtickspeed to 1k, nothing 
![image](https://user-images.githubusercontent.com/32142731/197861764-33019f84-21bc-4a7f-a6dd-4d324e2b2eab.png)

**Comment by CopCorvette** [comment]
Ok! Problem solved! It's been a while since i updated this mod and a bunch of other mods apparently was an issue with the Build 31 1.18.2.

My apologies for not checking that before.

**Comment by Flanks255** [comment]
you are fine, looks like this was actually caused by the same thing that caused another problem that i fixed, funny.

apparently grass decides if it can be grass by if the block above it blocks light, which, before the fix, some of the lights did, despite emitting light lol.
