### ISSUE TITLE
minecraft 1.19.2

### ISSUE THREAD

**Issue by kasperke** [Flanks255/simplylight#35]
Hi,

it doesn't work with the popular "Better Minecraft Forge BMC3" mod packs. It's 19.2 ...tried  simply light 19.3 and version 18.2.
Any possibility to make it work. There are so little good light mods like yours.

Kasper

**Comment by Flanks255** [comment]
do you have a crash log to help?

**Comment by kasperke** [comment]
[crash-2023-03-11_14.44.30-fml.txt](https://github.com/Flanks255/simplylight/files/10948641/crash-2023-03-11_14.44.30-fml.txt)

**Comment by Flanks255** [comment]
have you tried the version for [1.19.2?](https://www.curseforge.com/minecraft/mc-mods/simply-light/files/4016401)

**Comment by kasperke** [comment]
https://www.curseforge.com/minecraft/mc-mods/simply-light   where can i find it? Btw do i have to install : Requires
Shadowfacts' Forgelin - Kotlin language adapter. (1.12.2 Version only) (1.12.2 ONLY) [Shadowfacts' Forgelin - Kotlin language adapter(1.12.2 Version only)](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin)  also

**Comment by kasperke** [comment]
i tried all the combination. I have to make sure that simply lights works before i start building in a new world. I used it in most of my worlds.

**Comment by Flanks255** [comment]
that link in my comment goes directly to the 1.19.2 version, [here it is again](https://www.curseforge.com/minecraft/mc-mods/simply-light/files/4016401)
or if you go to the [files page](https://www.curseforge.com/minecraft/mc-mods/simply-light/files) its like the third on the list.

forgelin is only for the 1.12 version of the mod.

**Comment by kasperke** [comment]
oooh dang..stupid me.I'm getting to old for this (55).  It's under files. Sorry to take up all your precious time..next time your here in Belgium...i will buy you a nice Flamisch beer. Btw it works like a charm.
