### ISSUE TITLE
Illuminant Slab rotation

### ISSUE THREAD

**Issue by Sitocie** [Flanks255/simplylight#42]
**Describe the bug**
Illuminant Slab rotation seems somewhat random at placement. There's no air pockets or anything around the block, but the rotation of the block is shifting based on... nothing it seems?

I've tried:

- Replacing them (Mining them and picking them up, placing them again)
- A wrench for rotation
- Mining the blocks around it and placing them again, also replacing the lights and all the variations for those two

**Screenshots**
![javaw_7HKE88egWa](https://github.com/Flanks255/simplylight/assets/98874619/a531eab7-2d1d-43e3-9ca1-42b7375d03de)

Simply Light 1.19.2-1.4.5-build.42

**Comment by Flanks255** [comment]
They rotate to sit against the block that they are placed on.
![image](https://github.com/Flanks255/simplylight/assets/32142731/ecd97fa4-dc38-4d81-830c-e8dbb628b681)

The only exception to this, is if another slab/panel is what you are placing it against, in which case, it matches the rotation, unless you crouch.

**Comment by Sitocie** [comment]
I managed to capture it live so I'm not misunderstood. I forgot to mention that I'm playing the mod on ATM8 if that matters at all.
![javaw_isAQCgsco0](https://github.com/Flanks255/simplylight/assets/98874619/a2f267b0-81b5-4a44-9834-175754820fdd)
**NOTE: It fixes itself after x time / client restart**

**Comment by Flanks255** [comment]
ohhh, i see, it isnt rotating, the connected textures are disconnecting.

Those blocks you are placing, do they have connected textures too?

**Comment by Sitocie** [comment]
They do eventually, when the structure is complete (Bigger Reactors mod)
The client restart fix still works for me though.
