### ISSUE TITLE
Light Colour with Complimentary Shaders + Multiblock lighting 

### ISSUE THREAD

**Issue by ZyrusHub** [Flanks255/simplylight#48]
Your mod that produces any sort of light with Complimentary Shaders + Multiblock Lighting gives off the same colour as a torch which has a yellowish hue to it.

Its kind of annoying as i like your mod but as the light of the mod should produce a white modern light it produces the same colour as a torch. I'm not sure if you could change this on your end but if you could this would be great for people using Shaders that provide multiblock lighting that want the full experience of modern lights in their game.

![2024-09-22_15 45 32](https://github.com/user-attachments/assets/de4df137-8d5b-4261-ba08-fddb48d93955)

**Comment by Flanks255** [comment]
Minecraft blocks just have a light value, that light does not have any color component to it, its just 0-15

No idea how shaders like that decide on the light color.
