### ISSUE TITLE
[Feature Request] ability to color the lights

### ISSUE THREAD

**Issue by Zygus42** [Flanks255/simplylight#5]
Would be great to have the lights in different colors.  Maybe with a right click of a dye on the block ?

**Comment by Z-Tunic** [comment]
This alongside lights that glow in the dark but gives no light level would be nice.

Neon Lights, go.

**Comment by FrozenPhoton** [comment]
R+
The recipe could be any light plus the desired coloured dye.

Also I like that suggestion for neon lights too, not sure what would be good for that though, I'd say obsidian but that could get annoying in survival...

**Comment by carstorm** [comment]
Found this github just to make this comment. I would love to be able to color the lights. I think, as suggested above, just using dye + the light would be  a great simple recipe to achieve this.

**Comment by penguinsane** [comment]
Echoing the sentiment of others. Very simple, lovely mod. The only thing I would like is the ability to dye the lights.

**Comment by Foozey** [comment]
Agreed, dying the lights would be a great feature, and simple to implement.

**Comment by Flanks255** [comment]
Done in 1.16 v1.3.0, 1.17 soon
