### ISSUE TITLE
Cannot place item frames on Illuminant Blocks or Slabs

### ISSUE THREAD

**Issue by Tntmister** [Flanks255/simplylight#6]
When attempting to place an item frame on illuminant blocks, it will attempt to "use" the block instead of placing the item frame, even while crouching

**Comment by Flanks255** [comment]
Is this 1.12 or 1.14?

**Comment by Tntmister** [comment]
My mistake, apparently illuminant blocks can have item frames placed on them, but i have confirmed it doesn't work on illuminant panels and slabs, including the back side, tested on version 1.14.4-0.8.5 with forge 1.14.4-28.0.45
[Video](https://www.youtube.com/watch?v=YbrlH3J-zHQ)
