### ISSUE TITLE
simplylight 0.8.7/1.14.4 — illuminant rod placing incorrectly?

### ISSUE THREAD

**Issue by UnixRonin** [Flanks255/simplylight#7]
Illuminant Rod does not appear to place correctly, unless I am misunderstanding.  

The relevant (I think) description says, "Edge lighting strips that morph to fit against walls."  I assume that this refers to the illuminant rod; if not, it's not clear to me what it describes.  I see no other item that matches the description.  

What I *expect* from this description is that if I place an illuminant rod on a wall block, it will lie along the block, and if I put it into a corner between a wall and ceiling, it will tuck itself into that corner and lie along it.

In practice what is actually happening is that no matter where I place an illuminant rod, it stands directly out from the center of whichever block face it thinks it was placed on.

I COULD be misunderstanding what is supposed to happen here, but it seems to me this is not working as the description suggests is intended.

simplylight 0.8.7
Minecraft 1.14.4
Forge 1.14.4-28.0.49

**Comment by Flanks255** [comment]
So the Illuminant Rod is meant to be a replacement for end rods.
so that placement is correct, its description is this:
"A simple rod of light"
"Can be placed in any direction."

The edge light is the description you are quoting, it follows the blocks next to it.

**Comment by UnixRonin** [comment]
OK, when I look for simplylight items in JEI, I'm not seeing an edge light...?

**Comment by Flanks255** [comment]
Ah right, sorry, i have not implemented that in the 1.14 version yet, next on my list after i finish my current project.

**Comment by UnixRonin** [comment]
That would explain the confusion.  :)
