### ISSUE TITLE
Flickering light in inventory

### ISSUE THREAD

**Issue by d0ob** [Flanks255/simplylight#8]
Hi ! Really like the lamp models ! Really cool mod. 
I have an issue tho, not a bad one, since it's not that game breaking, but want your though on it ! 

_________________________
**Describe the bug**

So, when in the menu the light is flickering on my character rendering window, don't know how to describes it better, it cause some display issues with items and stuff. Also, I have a magnet mod and it seems to conflict a bit, item having kindof convulsions when coming to me ^^ ( Mod is JAM, "just a magnet" mod. ) As I said, nothing game-breaking, probably not from the mod iself, but for sure it's part from the mod, as it is around those lamps. (the corner top ones to be precise.)

**Screenshots**

Pictures would not be really clear I'm afraid, clip would be better I think but I have nothing to do it.. I'll try to take sceens still, if I can manage to capture the flickering it's still that.

**Crash/Conclusion**

No crash, but can the log help ? 
I'm on 1.12.2 with the 0.8.7 version of the mod, and Forge 14.23.5.2768.
( I know it's not the latest one, but since I have trouble with it, I'm sticking with the latest recommended one, with which everything is fine and straightforward. And If it's the cause of the problem, and you don't want to look for it besides recommanding to update I understand, glad it's not that bad of a problem ^^ )

Thanks for the lecture ! Good next, good work ! 

**Edit:**
Sorry it start to be a big text ^^ 
I have to say I'm pretty sure it wasn't flickering in my last world, so it can really be a conflict with a newly added mod ! I can provide my mod list but it would not be in chronological order, a screen of my folder maybe, to show what I installed last.

**Comment by Flanks255** [comment]
Most likely an interaction with another mod, probably a fluke.
